apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: eks-monitor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eks-monitor
  template:
    metadata:
      labels:
        app: eks-monitor
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
        - name: eks-monitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.env.CLUSTER_NAME }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
