replicaCount: 1

image:
  repository: ghcr.io/mayanksekhar/golang-eks-monitor-app
  digest: ""
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

env:
  CLUSTER_NAME: eks-monitor-demo

rbac:
  create: true
